[alloy]
log-stats = true
finalizer-elision = true
finalizer-safety-analysis = false
premature-finalizer-prevention = true
premature-finalizer-prevention-optimize = true
gc-disable = true

[rust]
codegen-units = 0
optimize = true
debug = false

[build]
install-stage = 2

[llvm]
download-ci-llvm = true

[install]
sysconfdir = "etc"

