[alloy]
gc-metrics = true
finalizer-elision = true
finalizer-safety-analysis = false
premature-finalizer-prevention = false
premature-finalizer-prevention-optimize = false

[rust]
codegen-units = 0
optimize = true
debug = false

[build]
install-stage = 2

[llvm]
download-ci-llvm = true

[install]
sysconfdir = "etc"

