# TOML configuration used for benchmarking Rust programs built with Alloy.

[rust]
codegen-units = 0           # Use many compilation units.
optimize = true
debug = false

[build]
install-stage = 2

[install]
prefix = "build/alloy-stage2-latest"
sysconfdir = "etc"
