# -*- mode: yaml -*-
# Config file for ReBench

runs:
    max_invocation_time: 360

benchmark_suites:
    binary_trees:
        gauge_adapter: Time
        command: "20"
        benchmarks:
            - ""

experiments:
    binary_trees:
        suites:
            - binary_trees
        executions:
            - alloy
            - rc
            - typed_arena
            - rust_gc

executors:
    alloy:
        env:
            DUMP_GC_STATS: ../../../results/binary_trees/alloy.log
        path: bin/binary_trees/
        executable: binary_trees_alloy
    rc:
        env:
            GC_DONT_GC: "true"
            DUMP_GC_STATS: ../../../results/binary_trees/rc.log
        path: bin/binary_trees/
        executable: binary_trees_rc
    typed_arena:
        env:
            GC_DONT_GC: "true"
            DUMP_GC_STATS: ../../../results/binary_trees/typed_arena.log
        path: bin/binary_trees/
        executable: binary_trees_typed_arena
    rust_gc:
        env:
            GC_DONT_GC: "true"
            DUMP_GC_STATS: ../../../results/binary_trees/rust_gc.log
        path: bin/binary_trees/
        executable: binary_trees_rust_gc
